export const cities = [
  { id: 1, name: 'Capital' },
  { id: 2, name: 'General Alvear' },
  { id: 3, name: 'General San Martín' },
  { id: 4, name: 'Godoy Cruz' },
  { id: 5, name: 'Guaymallén' },
  { id: 6, name: 'Junín' },
  { id: 7, name: 'La Paz' },
  { id: 8, name: 'Las Heras' },
  { id: 9, name: 'Lavalle' },
  { id: 10, name: 'Luján de Cuyo' },
  { id: 11, name: 'Maipú' },
  { id: 12, name: 'Malargüe' },
  { id: 13, name: 'Rivadavia' },
  { id: 14, name: 'San Carlos' },
  { id: 15, name: 'San Rafael' },
  { id: 16, name: 'Santa Rosa' },
  { id: 17, name: 'Tunuyán' },
  { id: 18, name: 'Tupungato' },
]
